#!/bin/bash
# Netlify Environment Variables Setup Script
# Run this to verify your Netlify configuration

echo "======================================"
echo "Netlify Environment Variables Checklist"
echo "======================================"
echo ""
echo "Go to: https://app.netlify.com/sites/YOUR_SITE/settings/env"
echo ""
echo "Required variables to add:"
echo ""
echo "1. GEMINI_API_KEY"
echo "   Value: Your Gemini API key from https://aistudio.google.com/apikey"
echo "   Example: AIzaSyAi1s-RtDw52CaaB80FeNC9DiBe8F5G75Q"
echo ""
echo "2. NEXT_PUBLIC_APP_URL"
echo "   Value: https://repoinfo.netlify.app"
echo ""
echo "Optional (for full features):"
echo ""
echo "3. GITHUB_TOKEN"
echo "   Value: Your GitHub personal access token"
echo "   Get from: https://github.com/settings/tokens"
echo ""
echo "4. STRIPE_SECRET_KEY"
echo "   Value: sk_test_... (from Stripe dashboard)"
echo ""
echo "5. STRIPE_PRICE_PRO_MONTHLY"
echo "   Value: price_... (from Stripe dashboard)"
echo ""
echo "6. STRIPE_PRICE_PRO_YEARLY"
echo "   Value: price_... (from Stripe dashboard)"
echo ""
echo "7. EMAIL_HOST, EMAIL_PORT, EMAIL_USER, EMAIL_PASS"
echo "   For sending receipt emails"
echo ""
echo "======================================"
echo "After adding variables:"
echo "1. Go to Deploys tab"
echo "2. Click 'Trigger deploy' → 'Deploy site'"
echo "3. Wait 2-3 minutes for deployment"
echo "4. Test at: https://repoinfo.netlify.app/api/health"
echo "======================================"
